### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by konstantinnovation** [hunter-teacher-cert/unit_plan-power-on-grade-2-5#1]
Sounds really good. 
You are aware you completed more of the outline than was required yes?

**Comment by theawilliams19** [comment]
> Sounds really good. You are aware you completed more of the outline than was required yes?

Hi Sam,

**Comment by A-Ufret** [comment]
> > Sounds really good. You are aware you completed more of the outline than was required yes?
> 
> Hi Sam, No, I hadn't realized. Glad though. That means we are ahead. Thank you for the feedback.

I did realize it was more than was required by last Thursday 🫣 😂... It just seemed to make sense to get down whatever we had ready so far (rather than forget it or have some part of it somewhere else). Thank you for the feedback ❣️
